---
- hosts: MGT
  gather_facts: false 

  tasks:
    - name: send mail  
      mail:
        host: 127.0.0.1
        port: 2025
        subject: 
        body: "{{ lookup('template', 'templates/update-success.j2') }}"
        from: 
        to:
        - "{{ hostvars[site-email-1] }}"
        - "{{ hostvars[site-email-2] }}"
        cc: 
      delegate_to: localhost
