---
- name: cam-check

  hosts: MGT
  tasks:
     
    - name:
      win_copy: 
      src: "/files/camcheck.ps1" 
      dest: C:\Temp\camcheck.ps1 
   
    - name: Run remote PowerShell Script
      win_command: powershell.exe -ExecutionPolicy ByPass -File C:/temp/camcheck.ps1
      register: {{ result.stdout | from_json }}

    - name: send mail  
      mail:
        host: 127.0.0.1
        port: 2025
        subject: 
        body: Cameras are offline
        from: 
        to:
        - "{{ hostvars[site-email-1]"
        - "{{ hostvars[site-email-2]"
        cc: 
      delegate_to: localhost
      when: return vaule =< 6 

   
  
